apiVersion: apps/v1
kind: Deployment
metadata:
  name: date-deploy
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: date
  template:
    metadata:
      labels:
        app: date
    spec:
      containers:
      - name: date-pod
        image: busybox
        command:
        - "/bin/sh"
        - "-c"
        - "while true; do date >> /data/pod-out.txt; sleep 10; done"
        volumeMounts:
        - name: date-vol          #<<이 이름과 아래의 volumes의 name은 일치해야 함(volume)
          mountPath: /data       #컨테이너의 실제 경로
      volumes: 
      - name: date-vol           #<<이 이름은 동일해야 함, 이 volumes의 name(이름)은 그냥 참조하는 이름이고, 실제 그 볼륨에 대한 속성 등의 정의는 아래에서 정의함. 여기서는 pvc를 사용하는 볼륨이라고 할 수 있을듯
        persistentVolumeClaim:
          claimName: date-pvc    #<이미 만들어져 있어야 하는 pvc 이름
