apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: 637423586845.dkr.ecr.ap-northeast-2.amazonaws.com/github-action-test:backend-v2.1.0
          ports:
            - containerPort: 8000
          env:
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: openai-api-secret
                  key: OPENAI_API_KEY
            - name: Endpoint
              value: testdb.cfmq6wqw0199.ap-northeast-2.rds.amazonaws.com
            - name: Port
              value: "3306"
            - name: Username
              value: admin
            - name: Password
              value: Saltlux12345!
            - name: Database
              value: multimodal_final_project